### ISSUE TITLE
Kodu güncelleyebilir misin?

### ISSUE THREAD

**Issue by mirzafly** [tingirifistik/BTK_Akademi#1]
Merhaba kodun çalışmıyor api sistemi sanırım değişmiş hata kodu:
`C:\Users\Administrator\Documents\GitHub\BTK_Akademi>python indir.py -u https://cinema8.com/raw-video/MXBWzaJn?c=js-api
76_00_sifirdan_ileri_seviye_python_programlama_sadik_turan_GIRIS_.mp4 --> Indiriliyor...
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\BTK_Akademi\indir.py", line 51, in <module>
    download(args["url"], output)
  File "C:\Users\Administrator\Documents\GitHub\BTK_Akademi\indir.py", line 24, in download
    f.write(requests.get(json_file["url"]).content)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?`

**Comment by tingirifistik** [comment]
api degismis, bir ara duzeltecegim.
